version: "3.9"

services:

  backend:
    image: 220282357772.dkr.ecr.ap-southeast-2.amazonaws.com/realestate-api:latest
    container_name: realestate-api

    env_file:
      - .env

    expose:
      - "5000"

    restart: always

  frontend:
    image: 220282357772.dkr.ecr.ap-southeast-2.amazonaws.com/realestate-client:latest
    container_name: realestate-client

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: always